- name: Check the user home directory exists
  stat:
    path: "/home/{{ user.name }}"
  register: user_dir
  tags:
    - ssh

- name: Create a ssh directory
  file:
    path: "/home/{{ user.name }}/.ssh"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0700
  when: user_dir.stat.exists
  register: create_ssh_dir_result
  tags:
    - ssh

- name: Check the ssh directory exists
  stat:
    path: "/home/{{ user.name }}/.ssh"
  register: ssh_dir
  tags:
    - ssh

# When use it, you should create a directory of authorized_keys/{{ user.name }}/ and
# put public keys into authorized_keys/{{ user.name }}/{{ inventory_hostname }}.
- name: Setup authorized keys
  copy:
    src: "authorized_keys/{{ user.name }}/{{ inventory_hostname }}"
    dest: "/home/{{ user.name }}/.ssh/authorized_keys"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0600
  when: ssh_dir.stat.exists
  tags:
    - ssh
