---
- name: Check the user home directory exists
  stat:
    path: "{{ user.home_dir.rstrip('/') }}"
  register: user_dir
  tags:
    - ssh
    - ssh-check-user-home-directory

- name: Create a ssh directory
  file:
    path: "{{ user.home_dir.rstrip('/') }}/.ssh"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0700
  when: user_dir.stat.exists
  tags:
    - ssh
    - ssh-create-ssh-directory

- name: Configure authorized keys
  copy:
    src: "{{ user.authorized_keys_file }}"
    dest: "{{ user.home_dir.rstrip('/') }}/.ssh/authorized_keys"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0600
  when:
    - user_dir.stat.exists
    - user.authorized_keys_file | length > 0
  tags:
    - ssh
    - ssh-configure-authorized-keys
